temp <- read.delim("household_power_consumption.txt", header=TRUE, sep=";")
for(i in 3:9) temp[[i]] <- as.numeric(temp[[i]])
temp$Date <- as.Date(temp$Date, format="%d/%m/%Y")
temp2 <- subset(temp, temp$Date>="2007-02-01" & temp$Date<="2007-02-02")
temp2$Time <- strptime(paste(temp2$Date, temp2$Time, sep=" "), "%Y-%m-%d %H:%M:%S")
png("Plot2.png", height = 480, width = 480)
par(mar=c(3,4.1,4.1,2.1))
plot(temp2$Time, temp2$Global_active_power/1000, type = "l", ylab = "Global Active Power")
dev.off()